### ISSUE TITLE
FoxTelem hangs SatPC32

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#278]
I'm not sure if this relates to #230 or not.  But I have had a number of problems with FoxTelem and SatPC32 interaction.  The latest:  If I check "Log Frequency" and "Read Az/El" in settings and then leave SatPC32 and FoxTelem running for a couple days, I come back and find SatPC32 frozen.  It is marked "not responding" by Windows (10).  I have been unable to kill it except by going to the task manager and forcing it to exit.  I am also using an LVB tracker, and that auxiliary program also has to be killed with the task manager.  Without those two checkboxes in FoxTelem, it runs for weeks at a time.

**Comment by WA4SCA** [comment]
Does the freeze always occur at 23:59:59 local, or some other specific time?  I have had a problem, now seemingly mostly solved, where every few days SatPC32 and the rotator server, a different one from Burns', would freeze at local midnight.  It didn't matter whether SatPC32 was displaying UTC or local.  Both were non-responsive, but consuming about 20% of the CPU until killed.   The fix was cleaning out all the scheduled events which ran at local midnight, and rescheduling them to random times.  Since then, I see the problem perhaps once a month, if that.  I haven't been able to find anything in the logs which is close in time.  

I never associated the problem with FoxTelem, only SatPC32, but they were always running together.  FoxTelem is always set for local time rather than UTC.  Unfortunately, it has proved impossible to duplicate in a controlled fashion to compare results.

**Comment by burnsfisher** [comment]
Aha.  You know I never looked at the time on SatPC32 when it froze.  

BTW, I'm using SabreTrak as the rotor type in SatPC32 (at the suggestion of Mark Hammond) although I use the AMSAT controller and Yaesu rotator.  As I recall I had the same problem selecting Yaesu in SatPC32.  

You might try turning off Log Frequency and Az/El in FoxTelem, Alan, just to see if we are talking about the same thing.  In the meantime, I've turned them back on to see if the freeze happens just at midnight.

**Comment by burnsfisher** [comment]
Ok, sigh.  I seem to be back in "random failure" mode this time.  First, it appears that SatPC32 did not freeze either at midnight OR at a pass.  However, this time FoxTelem crashed.  I took a screen shot of the error message.  Note that I happened to look at it just after a pass, and I'm not sure if it crashed during or after it.   I should also add that I am looking at it remotely with AnyDesk, which in my experience has worked flawlessly since Alan suggested it.  It is possible, though, that FoxTelem crashed just as I connected to it.

Worse, I tried to restart FoxTelem and I get a message saying something is wrong.  I'm assuming it must have screwed up some data files somewhere somehow.  Again, a screen shot is included.
<img width="1196" alt="screen shot 2017-08-05 at 5 19 46 pm" src="https://user-images.githubusercontent.com/2413372/28998854-2527c384-7a03-11e7-9195-487ab7d741ef.png">
<img width="929" alt="screen shot 2017-08-05 at 5 21 21 pm" src="https://user-images.githubusercontent.com/2413372/28998855-28a0d4d8-7a03-11e7-8011-bb2161161867.png">

**Comment by burnsfisher** [comment]
I just realized that the FoxTelem error message has some text that looks like it includes 'Herci' in it.  I was (several hours ago) testing a Fox-1D flatsat which probably (almost certainly) sent some 1D telemetry on 145.980 (the 1A frequency).   After I dismissed the error message, I selected the input tab and it all seemed to still be running, so it is possible that the error actually happened more like 1100 than 1720 (EDT) when I actually noticed it.

**Comment by burnsfisher** [comment]
I'm going to separate these two issues.  One of them is definitely caused by by experimenting with Fox-1d.  The other is still a bit unclear.  I think I'll close this and open two separate ones to avoid confusion and yet so as not to lose what is here.
