### ISSUE TITLE
Some min/max values are backwards: Battery current, panel temps at least

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#295]
When you display the converted (not raw) values, it appears that the min is greater than the max.  This is in FoxTelem and also the health web display.  I suspect this may be a case of some sort of issue with the minus sign.  In the case I am looking at the battery would be charging, although the raw numbers are relatively low.  I just set the battery to discharging and now I see the following:

RT:  -66.5  MIN: 73.8  MAX: -348.2

Checking a couple others with possible negative values, it looks like RSSI is correct.  There are some bogus temps that are reading negative, but I have nothing else that is both plus and minus. Panel temps are also inverted when looking at converted values.

I'm labelling this 1E, although it is probably an issue with them all.  It's just that 1E may be the first that has operational battery telemetry.

**Comment by ac2cz** [comment]
I downloaded the server data to look at this.  The raw values and converted values for Battery Current are:
1859 = 5.3mA
1848 = 17.7mA
1870 = -7.0mA

Battery Current zero is currently set to -1.839.  I think that is a voltage from the ADC.  This is a value that we calibrated for 1A but have not been able to use since.  We likely need to set the zero value again.

Anyway, given that I calculate the values as follows:
current = (raw * 2.5/4096 - 0.05) * (-1.839 + 2)*1000

Assuming that is all correct, and a higher ADC value is a lower current, then I need to reverse the sense of High/Low.  I have a setting for that in the layout config.  The "Line Type" is set to 4 = "DISPLAY_ALL_SWAP_MINMAX".  

This Line Type is currently set for Solar Panel Temp on 1A, but I don't think it is used for any other values. If we have other values where the ADC value rises as the value falls, then we should also set this Line Type.

**Comment by burnsfisher** [comment]
I think battery current is the only current that can be plus OR minus.  The question is, which one is charge and which is discharge?  I'd say that - is discharge, and I think that is what it is doing.

**Comment by ac2cz** [comment]
Fixed in v1.05p.

Note that this does not change how the data is stored, only how it is displayed in the FoxTelem screen.

**Comment by burnsfisher** [comment]
I don't think this is fixed for the panel temps.   Unfortunately, this will show up fairly extremely in all the birds with MPPT because they will all have nearly 0 when the panel voltage is 0.  I say unfortunately because I should probably have changed this in the flight software so it did not store when the voltage was near 0.  So the high value will usually be essentially useless.  But whatever---it does show in the min box in FoxTelem 1.05p.  BTW, perhaps you should put "---" either when the raw min is below some number like 10.  That will result in fewer complaints/worries.

**Comment by ac2cz** [comment]
Moved to release 1.05 given RadFxSat (1B) has MPPT.  I'll see if I can get this into the release.

**Comment by ac2cz** [comment]
v1.05q will address the MPPT Temps and hide values where they are bogus.  I have no way to filter out the high values, so the high value will typically be hidden.

**Comment by burnsfisher** [comment]
I concur that bogus values are hidden.  Thanks.

You said it was a "part fix" and I think that is because you are still displaying what is really the minimum temperature (the highest raw value) as MAX.  The highest raw value actually equates to the lowest temperature, and thus the only valid value should really show as MIN.

**Comment by burnsfisher** [comment]
I removed "critical", added 1C/1D (since the problem will be there also) and assigned back to Chris for when you get around to it.

**Comment by ac2cz** [comment]
LINE TYPE 4 = SWAP_MIN_MAX was applied to the Solar Panel Temperatures for Fox1E.  This was already in place for RadFxSat, 1C and 1D.  I must have just missed it for 1E.
This will ship with v1.05t, which I am really hoping is the final release for 1.05!
