### ISSUE TITLE
Fox-1E Radio PA Current formula is wrong

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#302]
The raw value 2698 turns into 197.6ma.  It should as follows.

First turn 2698 into an A/D voltage using the IHU A/D table.  Call this v.

Then current in amps is      v/(50*.1)
It should, of course, be displayed as milliamps as it is now.  So 2698 should turn into about 400ma (depending on the IHU table).

**Comment by ac2cz** [comment]
PA Current today uses conversion 10 which is the Fox 1A CONVERT_PA_CURRENT.
That formula is implemented as follows:
paVolts = rawValue * 3.0/4096;
paCurrent = paVolts / 50/0.2;
return paCurrent * 1000;

So the formula described above is the same with two key differences.
1. You say "use the IHU A/D table" vs 3.0/4096
2. You say current is v/(50*0.1) vs v/(50*0.2)

So my first question is, should I be using the IHU_VBATT lookup table for this.  Is that the same as the IHU A/D table?  Should I have been using that on Fox-1A whenever the 3V sensor is used?  I always use 3.0/4096, except when measuring VBATT.

Secondly, is it 0.1 vs 0.2 because the current shunt resistors are different on 1E to 1A?

**Comment by burnsfisher** [comment]
FIrst answer:   What you really want to do is to use the IHU_VBATT lookup table for all the values channels that use the IHU as the A/D.  Except for 1A, that would be all of the 4095=3V conversions.  On 1A, the PSU values are also 3V but are linear.  Put another way, all the RF values and IHU values for Fox-1A through D plus Exp4 temp use the table.

**Comment by burnsfisher** [comment]
It appears that the FM transmitter uses a shunt resistor of 200 milliohm and the 1E PA uses 100 milliohms, so yes, that difference is in the hardware.

**Comment by ac2cz** [comment]
New conversion in v1.05p
