### ISSUE TITLE
Name of spacecraft must match Nasabare.txt

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#417]
#395 mentions a related issue, but that is fixed.  The current version 1.06f1 has a related problem. The logic that fixes 395 apparently checks nasabare for a satellite with the same name as the spacecraft in FoxTelem.  Thus, you MUST name RadFxSat AO-91 or you get no keps.  Worse, the default name for Fox-1B when you install a new FoxTelem is RadFxSat.

Of course the name in nasabare also will change after launch, but probably only once.

**Comment by ac2cz** [comment]
I don't see how this is a bug. I have already changed the default name in
new releases.

I asked about the name ahead of the last launch, but no one would tell me
what it was going to be. So, yes, you have to change it.

One of the error messages already tells you to make sure the name matches.

**Comment by burnsfisher** [comment]
No, certainly  you don't get the Oscar number till it is successfully in orbit.  I downloaded 1.06f1 just in the last couple of days for FIAB and it said RadFxSat on the tab, which is not right.  Understand that that one is not fully released, but I suppose that is the only real bug part of this.

Hmm.  Yes, I guess the message said that the s/c name had to match, but I was not sure what the possibilities were in Nasabare.  Had to grep through it with RadFxSat, Fox-1B, finally thought of AO-91. 

Again, hmm.  I think for huge feature creep, there might be several things that could be downloaded just as you now download the T0 times.  One of them would be FOX2=AO-91 etc.

**Comment by ac2cz** [comment]
The name is correct in 1.06f.  The name is specified int he radFxSat_fm.MASTER file in the spacecraft dir.  If you only installed the jar file, then you will not have picked that up.  Or if after installing you got a message saying something like "there is a newer spacecraft file, do you want it" and you said no, then you would not get it.

I will consider the auto update of the name, but that would make this an enhancement and not a defect.

**Comment by burnsfisher** [comment]
Sure, enhancement is fine.

**Comment by ac2cz** [comment]
Re-reading this after the fact, I think the spirit of this issue is that you can't give it one name and use another name to search the keps.  I will think about adding another field, but it would also be one more thing to get wrong.  We likely need a checkbox which defaults to "yes" saying "Use SatName as the Name to looup in Keps file".  If you uncheck it you could add a separate name.  Something like that.

**Comment by ac2cz** [comment]
This will be implemented with a "Display Name" that is initialized to the same name as the Keps Name.  I need to decide if there is a checkbox which ties them together for users that do not care about separating them.

**Comment by ac2cz** [comment]
This is in 1.08j

**Comment by ac2cz** [comment]
In testing Alan reports the following issues:

In one I had all four Fox spacecraft selected for tracking, upper right on main page. Only AO-85 carried through. In the other single satellite versions, AO-91 and AO-95, I had to reselect tracking.

FOX1E_em.dat reported as mising displayName.  This is likely because I supplied a new FOX1E_fm.dat file.  So the em file is redundant.  But that is not obvious to the user.  We should spot we have both and remove one.

In all three cases, when I tried to change the selected Mode, it saved with no error message, but when I went back to the satellite page, it had not in fact changed.
