### ISSUE TITLE
Missing last CAN message in each payload V1.07m

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#492]
I am sending 22 can packets, which should fit into 4 payloads with 6 in the first 3 and 4 in the last.  For the payloads with 6 can packets, FoxTelem displays only the first 5.  UW's symptoms indicate that the last one might also not be getting sent on the network.  The payload with only 4 can packets seems ok.

**Comment by ac2cz** [comment]
I have reproduced this.  The last CAN packet was being lost when the payload was full.  It is fixed it in 1.07n.

This bug was in some common code between the WOD and Health CAN payloads.  I don't have a good way to test the WOD records at the moment.  Let me know when there is a suitable IHU build and a test method to use.

**Comment by burnsfisher** [comment]
Confirmed.  This appears to work correctly with health packets from UW's board with their power distro firmware loaded.  Thanks!
