### ISSUE TITLE
DUV decoder ( it is not issue, just a question)

### ISSUE THREAD

**Issue by keramaisa** [ac2cz/FoxTelem#514]
Hi :) 

I have a quite odd question.. but I hope you can hep me somehow..
I am trying to make a (and here is a first question) de\modulator for DUV data, basically I have wav file of DUV telemetry and I want to do some stuff with matlab on it. I want to cut the audio frequencies (higher then 200kHz) and play only with the data. But I am hesitating if the wav file we receive is a analog signal or the digital one, because here I am not sure if to modulate or demodulate, basically I just want to do the reverse action on that signal, so if its analog FSK modulated signal I want to demodulate it to digital form (am I thinking right ? ) and if its already digital, like string of bits, I want to modulate it and have analog signal. I hope it is not to messy what I wrote .. Thank you for any advice :)

**Comment by ac2cz** [comment]
Hi @keramaisa, always happy to try to help people writing this type of code.

I assume the wav file is a recording of the Fox spacecraft.

You should be able to quickly tell if the wav file is FM modulated carrier or the audio.  Open the wav file in an audio analysis program like Audacity (which is available on Windows, Mac, Linux and is free).  Play the file and see if you can hear the audio.  If you can then the FM demodulation has already been done.  You can also look at the waveform. If it looks like an audio waveform and when there is no audio above 200Hz you can see the data bits, then it is already transformed from FM to audio.

**Comment by keramaisa** [comment]
Hi :) Thank You for quick resposne, sorry it took me few time to respond, but I was trying to understand that. I used the file from FoxTelem recordings (AF file). Yeah it looks like audio wave, though I wish I could add a screen, but except two parts when it looks like audio (and this is the time when there is a message from satellite transponder, I don't know what exactly she is saying, but not important) and the rest of the duration I can hear only noise, though FoxTelem decodes data. I tried to display spectogram, but still I can't understand few things. From what I have found in manual : DUV data contains FM audio (0-200Hz) and that is untouched by the decoder + the rest should be FSK signal.. But when I am not using FoxTelem to play that file, just use the wav file from recordings I should supposed that this is already digital signal, right ? With audio on the same band. And I was wondering how it is done, that we have encoded data (FSK) and still on the same frequency we have the FM audio.. This is beyond my imaginatio of signals hah

**Comment by ac2cz** [comment]
@keramaisa the test file you are looking at is audio if it ends with AF.  The radio signal has already been demodulated from FM.  This is the safe mode beacon from the spacecraft.  It contains both audio and data.  We create it as follows:
* A telemetry data stream is created on the spacecraft at 200 bits per second.  For a "1" the audio value is high and for a "0" the audio value is low.  It is filtered so that the audio spectrum is less than 200Hz.
* The audio message you hear comes from a recording on the spacecraft, but we use the same method when the transponder is on.  This audio message is filtered so that the audio spectrum is greater than 200Hz
* We then add the two audio signals.  Note that some people would say that we "mix" them, but as Radio Amateurs we think of mixing as multiplication, which changes frequencies.  In this case we add the audio and the frequencies do not change.  We now have the data from 0-200Hz and the spoken message from 200Hz and more.

You can recover the data by filtering it.  If you open the audio recording in Audacity, then choose "Effects > Low Pass Filter", you can experiment with 200Hz filters to see if you can recover the bits.  If you zoom into the signal with the magnifier in Audacity, you can see the actual audio waveform. As you filter it the high frequency noise is removed, leaving you with the data bits.

**Comment by keramaisa** [comment]
@ac2cz one last question though .. I was trying to plot the spectrum using the downlink frequency as the carrier, I’m not sure though if that was good, is that this freaquency you used for modulation ?

**Comment by keramaisa** [comment]
I was just trying to modulate that signal again, to plot the analog wave, but I didn't know what to use as a carrier frequency to modulate it. I used downlink one, but I wasn't sure if that is correct.
Joanna

**Comment by ac2cz** [comment]
I'm closing this as its not a FoxTelem issue.  Feel free to email me with any other questions.
