### ISSUE TITLE
Selecting a record in the bottom text section behaves oddly on panels above

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#529]
I'm not sure I can explain this reliably, but I'll try.  First, I've only seen this with downloaded data, but that may or may not be relevant.

- Download data for a satellite.  AO-85 works and I don't know if size is relevant.
- Pull up the bar across the bottom so the next form of records shows.  Expose 10 or so. 
- Select a record, and the panels above update to display that record.
- Use the arrow keys to move up and down, including below the bottom most readable record.
- After a while most of the displays stop updating when the selected record is visible above the bottom of the window.  On mine, time of the last max record updated, but the realtime time and min time did not.  The enclosed screenshot is from V1.08, but it has happened on 1.07 versions as well.

P.S. I feel like I may have mentioned this, but I can't find either email or issue.  
P.P.S In the picture, you can see that the MAX time is in the vicinity of the time of the selected record, but that MIN and REAL times are not even close.  
![screenshot 2018-12-17 17 32 12](https://user-images.githubusercontent.com/2413372/50119849-f048f400-0221-11e9-9663-54d210f8f657.png)

**Comment by burnsfisher** [comment]
I originally marked this as critical since it is important for examining data from AO-85 and 95.  I just discovered that 1.07d works ok, so we could use this older version.  That makes it less critical, so I marked it only high.

**Comment by burnsfisher** [comment]
This happened with V1.07v using AO-85 data, by the way.

**Comment by ac2cz** [comment]
I can reproduce this in 1.07w.  Good grief.  What a strange bug.  I'll try to fix in this branch so that we have it in 1.07 and 1.08.

**Comment by ac2cz** [comment]
I can't reproduce with AO-92 data.  I see a lot of empty files and missing resets in the latest AO-85 data.  I wonder it that causes the problem.  One additional strange thing is that once this bug has happened, when you re-open FoxTelem the data does not show at the top of the tab at all.

**Comment by ac2cz** [comment]
This might be an issue with the extract of the data on the server rather than with FoxTelem.  It is trying to navigate a corrupt set of files.  Luckily the data on the server is really in the database and is not corrupt.  Just the extract into the files is suspect.  We seem to have 2 files mentioned in the index that point to the records that disappear.  One of the files is empty and is for a single reset, the other contains lots of data across multiple resets.

**Comment by burnsfisher** [comment]
Hmm.  First, this reproduces on a Mac.  Second, I agree that it does not seem to happen on AO-92, and it happens easily on AO-85.  But AO-91 seems to have a slightly different issue.  It appears that nothing before 42/1299242 has downloaded from the server, so naturally, when I try to go backward from there nothing happens.  However, it is not the same issue--when I start selecting records forward in time, that seems to work ok.

**Comment by ac2cz** [comment]
This is also a bug on the server extract.  FOXDB stores the data in files called SEGMENTS with the start RESET and UPTIME in the file name.  There is an index file that ends with idx that says how many records are in each SEGMENT.  When FoxTelem adds some data to the DB it checks to see if the SEGMENT exists, if it does not it creates it.  In that way if we have 5 records for RESET 916 and then a new record for RESET 917 it starts a new SEGEMENT for 917.

The server extract packs the files full of 1000 records and does not start a new file each time there is a new RESET.  This actually works, even though it was not the design.  Except it seems to break with lots of little short resets and gaps.  It breaks as you scroll with the arrow keys because it is creating the missing SEGMENTS.  But they have no data in them.  

So the script on the server needs to be updated to respect the way the data should be presented.  All downloads will be fixed when this is cleaned up, though you may need to reset the FOXDB directory.  In fact I am going to add the cleanup to the download for future versions.

**Comment by ac2cz** [comment]
There were two bugs in the end.  The bug on the server was as described above and is fixed.  New data will download correctly.

But MIN/MAX records are not selected correctly when you click on a row.  It does not find the previous one from the RT reset/uptime reliably.  That is now fixed in 1.07y and later.  This required a change to the core FOXDB logic and there is a small amount of danger with that.  So I will need to extensively regression test to make sure nothing is broken.

**Comment by ac2cz** [comment]
There is one odd behavior, but I think we will declare it as valid.  In the screen shot below I have just started FoxTelem with test data.  The reset/uptimes at the top of the screen are for the latest records in FOXDB.  Note that the uptime for the min is after the uptime for the RT record.  

When I click on the top row in the table the time stamp for min changes to reset 133 uptime 4295 because that is the last min record _before_ the uptime for the realtime record, and that is how the query works.  So the data on the screen updates to show that.  Let me know if you agree that is valid.

![image](https://user-images.githubusercontent.com/14824793/54073244-f5cb3e80-4252-11e9-9e88-a67e5fc71d9e.png)

![image](https://user-images.githubusercontent.com/14824793/54073288-5eb2b680-4253-11e9-8699-72118e7c0c47.png)

**Comment by burnsfisher** [comment]
So I think the thing is that the MIN and MAX records are not shown in the
table, so when one is chosen you go backwards to find the previous MIN/MAX
records.  But in the first case, there was a MIN record received (or in the
DB) which was newer than the newest REALTIME record, so as long as nothing
is chosen from the table, that is displayed.

Sure, I think that makes sense.  It may get the occasional question, but oh
well.  I guess one question I would have now is whether there is any way to
"get back" to displaying the latest of everything.  And is it the same
question when you have selected a table entry and a new payload arrives
from the satellite?

Thanks for all the work on this!

**Comment by ac2cz** [comment]
Restarting FoxTelem definitely displays the latest of everything.  If you are listening live and a later record turns up then that will be shown at the top of the window.

Close this if you think its now fixed

**Comment by burnsfisher** [comment]
Ok, thanks!
