### ISSUE TITLE
Null Pointer Exception after closing and re opening FoxTelem 1.08d

### ISSUE THREAD

**Issue by garrettdreyfus** [ac2cz/FoxTelem#543]
Upon closing and reopening FoxTelem we encountered this error.

This was our second time opening FoxTelem. Before the first time we deleted the contents of the log files and started fresh.

![image](https://user-images.githubusercontent.com/3867825/53142084-24e96c80-353f-11e9-948e-a499fe13ecb7.png)

**Comment by ac2cz** [comment]
I have seen this error too.  It is a timing issue at startup where it is reading the data store before it is ready.  I have not managed to work out exactly where because the issue vanishes when you try to debug it.  Closing and reopening again is a work around in development.

**Comment by ac2cz** [comment]
I added some defensive code to wait for the data store to be initialized before starting the decoder and writing records.  This will be in 1.08e.  

It is tempting to apply the same defensive code to the production branch - 1.07, but for now I will hold off.  I think this is an issue because of the volume of CAN packet layouts.  I have not seen this in earlier versions of the decoder.

**Comment by garrettdreyfus** [comment]
Awesome, thank you!
