### ISSUE TITLE
Upgrade from 1.07y to 1.09 looses tracking enabled

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#565]
When I upgraded from 1.07y to 1.09 on a rpi, it only remembered that AO-85 should be tracked.  I had to click on the other three to track them.  This seems vaguely familiar, so it might not be totally new.

I've labelled it Linux, but I don't know for sure if it is a problem ONLY on Linux or if it is related to #563

**Comment by ac2cz** [comment]
This is a side effect of the fact that I store some settings in the spacecraft config files.  e.g. max and min frequency, if it is tracked, etc.  Those settings are lost when  release a new spacecraft.dat file.  It gets overwritten.  I need to either write an upgrade script that pulls in the customized settings or split them out into a separate file.  Currently it is a bad design.

If copying the settings over is easy I will put in the next release, otherwise it will get pushed to 1.09

**Comment by burnsfisher** [comment]
Ok, thanks.  Pretty low priority.

**Comment by burnsfisher** [comment]
This upgrade from 1.08n to o lost the ground station name, which had the effect of not allowing uploads.  It also lost several of the tracking checkboxes.  However, that seems pretty likely related to another issue so I will close this one.
