### ISSUE TITLE
Could not parse and save frame

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#600]
On V1.08r:
It appears that Chris got this a couple times, and now another FIAB customer (Larry P) also got it.  I don't see that it is listed as an issue yet, so I'll start the issue.   I'll include screen shots of  Larry's messages:  
![Screenshot_20191123-095128_VNC Viewer](https://user-images.githubusercontent.com/2413372/69481827-c8272500-0de2-11ea-8601-76d6b71b8db5.jpg)
![Screenshot_20191123-095056_VNC Viewer](https://user-images.githubusercontent.com/2413372/69481830-ccebd900-0de2-11ea-9998-8e974a689907.jpg)

He also reports that when he attempted to restart, he got an "unable to read property file" message.

**Comment by burnsfisher** [comment]
More from Larry:  I have continued from the configuration file error, and found that the station settings were completely missing.  The spacecraft information was intact. The old received data appears Ok.

After setting up the station settings and re-sizing the audio and FFT windows, the operation appears to be normal again.  Fingers crossed.

**Comment by burnsfisher** [comment]
What logging would be helpful in tracking this down?

**Comment by ac2cz** [comment]
Thanks for logging this.  I have seen this issue at my station but it has not had the associated problem with the settings.  That could be a coincidence or it could be related.  So thanks for logging this

**Comment by burnsfisher** [comment]
And more from Larry:  After the crash, and after filling in the station information which was now blank, the restart seemed OK for a while.  But, as you suggested, things began to go downhill. There were some errors such as "USB library busy" that could not be dismissed.  Another restart also seemed OK for a while, but shortly there was loss of control of the dialog tabs, although the background tracking was still running.

At this point I ran "clearFoxTelemData.sh".  Operation since has so far been normal, with one exception.  The sub-windows for the spacecraft data now take up the entire window, as before they were only a fraction of the main window.  I have not found a handle to reduce their size.  Not a big deal, but different from operation before the crash.

**Comment by ac2cz** [comment]
There are two errors that occur at the same time.  There is the "Could (not) parse" error and then there is a NullPointerException.

The "Could (not) parse" error is for a Type 4 Radiation Experiment frame. This error happens when we fail to add a record to the database.  In my code the comment literally says "This should not happen".  Oh well.

I think the second error is then caused by the first.  This is the GUI display thread trying to retrieve the Type 4 frames and display them.  It asks for the latest list of frames.  It finds they are not in memory so it tries to load from disk.  That load then fails for some reason.

The cause is unclear.  It might be because the frame to save is corrupt.  It has reset 4776, but that is a valid number for AO-85.  That suggests that the rest of the frame is bad somehow and does not parse correctly, causing the crash.  On my own system I have seen this error and each frame in a row has an error.  That suggests that corruption is NOT the issue, but something else is going on.

It's possible that when corrupt records are initially saved they are added to the index, but fail to save to the disk.  So when the GUI tries to retrieve the latest records, it finds reset 4776 is the latest (according to the index), it tries to load the data and crashes.

The "Unable to read Properties File" error suggests that the properties were corrupted somehow.  That might have been because it was killed from task manager.

**Comment by burnsfisher** [comment]
Oddly enough I happened to look at my PC (which I have not looked at for a long time...in fact it is still running 'p'.  And had this (which I think is about what you said above):

<img width="910" alt="Screen Shot 2019-11-25 at 9 20 23 PM" src="https://user-images.githubusercontent.com/2413372/69594219-a5a33080-0fc9-11ea-89d7-e7d1c87003f2.png">

**Comment by ac2cz** [comment]
@burnsfisher yes that is it.  If you have not done anything, can you make a zip file of the directory with the data in it and send to me?

**Comment by burnsfisher** [comment]
Rats!  I have already start up 1.08s on this database and wiped it out.  But the good news (possibly) is that I think I had logging enabled.  Is the log useful and/or is the data directory still useful?

**Comment by ac2cz** [comment]
Burns, I think this one is fixed in 1.08w.  Can we close?  I have not see it in a while.

**Comment by burnsfisher** [comment]
Ok.  Will do.
