### ISSUE TITLE
Conversions in the Website look wrong for some values

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#612]
![image](https://user-images.githubusercontent.com/14824793/73761132-5bae9780-473c-11ea-8120-0decbcb96a67.png)

**Comment by burnsfisher** [comment]
Just a note that the MAX values are being transmitted incorrectly.  In other words, the web page is displaying some bizzare stuff for max because it is getting bad stuff.    The reflected power, of course, is a bit weird.  If it had the same conversion as fwd power, it should be the same value max--636.7

**Comment by ac2cz** [comment]
This was a max min MRAM issue and not a FoxTelem bug.
