### ISSUE TITLE
Units/scaling wrong for WOD Stored display in Spacecraft Status

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#619]
FoxTelem appear to be displaying the the actual number sent down for WOD Stored, but the label says (in 000s).  In fact that number is the actual number divided by 4.  So 37 should be displayed as 148 and the label and hover text should not say "in hundreds".

This was thought to have been fixed earlier (#297) but 1.08z has the old behavior.

**Comment by ac2cz** [comment]
Just for reference, when we have issues like this I don't go back and fix the original downlink spreadsheet.  I will make the edit directly in the layout.

I also realize that this fix may no really be needed, but I worked on it to test out the new conversions.

Right now there is no conversion on this at all.  So I will just multiply it by 4. I am using a curve that I called "com1_wodSize" that just multiplies by 4.  That showed me that we need to be able to String format these curve conversions, because it gave the answer 148.0 rather than 148.  I had already set it up so you can use the legacy conversions together with a curve, but it did not work for string results.  So that is fixed.  It uses a curve to multiply by 4 and then the legacy INTEGER conversion to format it without units.

This is in the next version 1.09k

**Comment by burnsfisher** [comment]
I'm not sure I understand what you did or whether I need to do anything for Golf.  I don't seen any conversion curves in Husky, 1E or Golf that say com1_wodsize (which must have been for Husky).  And 1E does not have conversion curves at all.  Is it fixed in code for 1E?  It looks right in Golf on 1.10b, although there is an odd line below WOD Stored in the panel (which may be my problem).

Is anything more needed anywhere?

**Comment by burnsfisher** [comment]
The odd line was my layout problem.  Two different data in line 2, none in line 3.  Fix in next push to you.

**Comment by ac2cz** [comment]
For 1E this is a fixed hard coded legacy conversion.  You should use a curve for GOLF.  

There is a conversion curve for Husky - HUSKY_SAT_conversion_curves.csv.  The line is labeled com1_wodSize and just multiples by 4.
