### ISSUE TITLE
Duplicate names in conversion curves hang on startup

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#649]
I copied a couple conversion curves to save them and forgot to change their names to "curve_save" or something.  FoxTelem hung on startup and required CTRL-Alt-Del etc to get rid of it.

This is low priority.  My error was fairly obvious.

**Comment by ac2cz** [comment]
I tested this by copying the last row in the conversion curves CSV.  I changed the data but left the name of the curve the same.  At startup I get this message: 
![image](https://user-images.githubusercontent.com/14824793/99979332-faac8a80-2d74-11eb-9586-a33f9fbfae85.png)

It did not hang.  I cleared the message and it started up fine.  It's possible I have added that message since you saw this.  Let me know if I need to test a different situation.

**Comment by burnsfisher** [comment]
Well that is really odd.  The same thing happens with me--I get that message now, and I have not changed anything.  My error that caused the hang must have been something more subtle.  If it happens again, I'll try to figure out more carefully, I'll close this now.
