### ISSUE TITLE
FoxTelem crash

### ISSUE THREAD

**Issue by abraxasneo** [ac2cz/FoxTelem#675]
For some time now, the foxtel has not started properly. Instead, it gives a lot of errors. I tried uninstalling and reinstalling in a different directory. it's not helping. I'm sending a screenshot. I am unable to stop the program. I have to kill the process.
![crash](https://user-images.githubusercontent.com/28750844/104897805-1d27e200-5979-11eb-99da-aac97acad324.jpg)

**Comment by ac2cz** [comment]
Hi @abraxasneo, sorry for the delayed response.  Did you fix the issue?  Can you tell me what version you are on so that I can track down the error?

**Comment by abraxasneo** [comment]
When I wrote to you, it was the newest version. 
Unfortunately, I couldn't fix it. I deleted the program and installed a new one, but still the same errors

**Comment by ac2cz** [comment]
Thanks for reporting this bug.  I have been able to reproduce it here.  I will fix it in the next version.

To reset the program go to your home directory.  If you are on windows it will be in C:\Users\USERNAME where USERNAME is the name of the account setup on that computer.  In that directory there is a folder called .FoxTelem  

Go into the .FoxTelem folder and delete all the files.  Then try starting the program again.

On the File > Settings menu there is an option called Debug Values.  Don't toggle that on until I release a new version.  That is where the bug is.

**Comment by ac2cz** [comment]
I have an updated release version 1.10d3 here: https://www.g0kla.com/foxtelem/downloads/test/

This should fix this issue and you should not get the error.  You will not need to go through the reset that I describe above.  Just install this new version and use it instead of 1.09.

This is a pre-release version for testing.  Let me know if you see any issues.

**Comment by abraxasneo** [comment]
Thank you for solving the problem
