### ISSUE TITLE
Auto band switch and FCD gain/BiasT can't be checked together

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#677]
Return center/Switch Modes can only be set when Auto-Start is checked.  But when autostart is checked, if it is not running you can't set the biasT and gain settings.  If you uncheck AutoStart and start you can set biasT etc, but that UNCHECKS Retune center. 

So in other words it is difficult to double check the settings, or to be sure that both settings are correct.

**Comment by ac2cz** [comment]
Suggestions on this?  The settings are not visible because when the device is stopped I release the USB interface.  So you can't adjust the settings when the device is stopped.  I could perhaps show it but greyed out.  Would that work?

I agree the dependence between Auto Start and Retune Center is confusing.  I decided not to merge the functionality of auto start and return center because you might have 3 copies of FoxTelem all listening to the same center frequency.  You don't want it to change.  But to save CPU you set them all to Auto Start.

**Comment by burnsfisher** [comment]
Hmm.  I understand that you don't want the functionalilty of center and autostart merged.  Or I think I understand it anyway.  Let me try a few thoughts:
1) Using multiple copies of FoxTelem with the same FCD requires some knowledge.  For example, you must know that you have to have the same LO frequency and that you have to choose an LO frequency that has all satellites visible.  (Sigh--only one now!)

--In other words, I would think that someone using multiple copies with a single FCD would be high end knowledgable anyway.  (BTW, remember issue (put number here) where I suggested that there should be some sort of communication between mutliple instances so that user knows which one is in control of the HID.  This might relate.

2) I'm not sure that (1) relates to why unchecking autostart has to uncheck retune, but you are the author here.

3) Having the HID setting grayed out but still showing there setting would be helpful, I think.

**Comment by ac2cz** [comment]
Also #553

**Comment by ac2cz** [comment]
I'm revisiting this for a potential 1E release.  I see that Retune Center is no longer locked to Auto Start.  If you check/uncheck Auto Start it does not impact Retune Center.  So you can uncheck Auto Start and run the decoder. You can setup the Bias T or other settings and then when happy click Auto Start again.

Does that close this issue?  It is already in 1.11g and you can test it there.

**Comment by burnsfisher** [comment]
Agreed.  That looks ok on 11g.  Thanks!
