### ISSUE TITLE
Foxtelem "Missing USB", CubeSatSim

### ISSUE THREAD

**Issue by Nanjavi** [ac2cz/FoxTelem#681]
Hi, I'm a student currently trying to get a [CubeSatSim](https://github.com/alanbjohnston/CubeSatSim/wiki) to work with Foxtelem, and there are a few things going wrong. 
1. I've been getting the “missing USB” error when I have the RTLSDR in the USB port
2. I don't think the issue is with Java or my devices because I've tried on a windows and Mac device and the same error appeared
3. I know there's nothing wrong with the RTLSDR dongle itself because SDRsharp is able to work with the dongle.
4. I've tried deleting and redownloading Foxtelem but the same errors show up
5. The other sources like a wav file, microphone array, and primary sound capture driver work when selected. 
6. I have only one USB port, and my flash drive and Bluetooth mouse work when plugged into it. 

I believe I have the drivers set up correctly for the RTL-SDR because the “couldn’t claim USB interface” error went away after we performed [certain steps.](https://www.rtl-sdr.com/getting-the-rtl-sdr-to-work-on-windows-10/) I don't think I'm using the E4000 tuner or Raspberry Pi. I would appreciate other solutions or any help with this issue. Thank you!
______________________________________________________________________________
RTL2832U R820T2
Windows 10
java version "1.8.0_281"
Foxtelem 1.10c3

**Comment by ac2cz** [comment]
Thanks for the report. Sorry to hear of the difficulty. The RTL device you have might not be supported by FoxTelem.  Do you have logging enabled?  Can you send me the log?  You can turn it on from the File > Settings window. The log is written in the log files directory.

**Comment by Nanjavi** [comment]
[FoxTelemDecoder20210212.log](https://github.com/ac2cz/FoxTelem/files/5969486/FoxTelemDecoder20210212.log)
Let me know if this wasn't what you're looking for. 
Thanks!

**Comment by ac2cz** [comment]
In the log I see: 
20210212000330: couldn't determine RTL2832 tuner type: device.DeviceException: couldn't open device - check permissions (udev.rule) [LIBUSB_ERROR_ACCESS]

That suggests that FoxTelem does not have permission to access the RTL.  Are you running this on Windows or Linux? 

If you are on Windows then make sure that another program does not have the device open.  For example, you need to exit SDRSharp because it will hold onto the Dongle and prevent other programs from accessing it.

If you are in Linux then you need to set the permissions on the udev rules so that the user who runs FoxTelem has access and you need to set the permissions on the USB device in /dev in the same way I expect.

**Comment by Nanjavi** [comment]
I'm on windows, but I'm pretty sure Google chrome was the only other application open when I ran it before. Regardless, I just ran it with ONLY Foxtelem open and the same errors showed up. I also tried plugging in the RTLSDR before I opened the app and after I opened the app to see if that made a difference. 

- When I plugged in the dongle before I opened the app, I got the "serious edt error". I clicked ok, but then Foxtelem never fully opened (I waited about 10 min). The third picture is what opened. The full GUI never showed up, and I had to restart my laptop to get it to close. 
- When I plugged in the dongle after I opened the app, I got the "serious edt error", but the program appeared to still be running as the start button now said stop instead of changing back to start. When I pressed stop and start again, I got the "missing USB device" error and the program stopped by itself. 

If it helps here are the errors:
![missing usb device](https://user-images.githubusercontent.com/69646946/107853624-b9a89d00-6ddc-11eb-8e5d-1b6557379d19.jpg)
![serious edt error](https://user-images.githubusercontent.com/69646946/107853626-ba413380-6ddc-11eb-975a-4f6387ca6c1a.jpg)
![loading logged data](https://user-images.githubusercontent.com/69646946/107854274-81a35900-6de0-11eb-81d7-e99d669e3807.jpg)


Thanks!

**Comment by ac2cz** [comment]
Can you tell me what type of RTL device it is?  It looks like it may not be supported by FoxTelem.  I have only implemented a subset of the rtl-sdr library.  If this is a common device then I could consider adding it.

**Comment by Nanjavi** [comment]
On the USB, it says:
DVB-T+DAB+FM+SDR
RTL2832U R820T2 TCXO+BIAS T+HF

Though, I think the RTL device is implemented. The instructions for setting up the [CubeSatSim ground station](https://github.com/alanbjohnston/CubeSatSim/wiki/Ground-Station) use Foxtelem with this same type of dongle. If it works for other people, I'd imagine the problem is with something else. I may just be inexperienced though.

Thanks for your effort so far!

**Comment by ac2cz** [comment]
I have a new release, version 1.09d, that might help you.  Download here: https://www.g0kla.com/foxtelem/downloads/test/

This does not fail when a most USB errors are hit.  It logs the error and tries to carry on.  If the issue you have is with the USB hardware / bus, then this might help.  It also adds several additional features for the RTL, such as wider bandwidth and frequency correction.

Even if this does not solve your issue, I would be very interested to here how it operates with the RTL that you have.

**Comment by Nanjavi** [comment]
It works! This version pretty much solved all the problems I had. The decoded telemetry shows up even when I plug in the dongle before or after I open the application. Changing some of the settings and deleting the old version of Foxtelem didn't mess anything up either. 

Thank you so much! I'll let you know if anything weird happens!

**Comment by ac2cz** [comment]
Thanks for the ongoing testing.  I have an updated release version 1.10d3 here: https://www.g0kla.com/foxtelem/downloads/test/

This splits the USB errors into fatal and non fatal.  With a fatal error the command is lost.  Non fatal errors can be safely ignored.  I now color the errors red only if there is a fatal error.  Even a low number of fatal errors can likely be lived with.  It might mean that the device was not on the right frequency when it was started or did not set the gain correctly. But most of the time it was fine.

Let me know what you see.  I think this is an important update and once if is tested I would like to release it to everyone.

**Comment by Nanjavi** [comment]
I'm not completely sure if you were looking for anything in particular, but here were some of the things that I noticed:

- In the bottom right hand corner, the "Audio Missed" would occasionally turn red. I didn't see a commonality between the times it did turn red though. Nothing other the "audio missed" turns red, and nothing appears after the "USB errors" label. 
![working screen](https://user-images.githubusercontent.com/69646946/108579513-c3eefd80-72ec-11eb-833c-866063b2cadb.jpg)
- Because I'm working with a CubeSat, I have tracking turned on for CubeSATSIM-BPSK and FSK and Fox-1E. When I go into those tabs no values are changing. (Though that's probably because the CubeSat doesn't consistently send out telemetry).
- The CubeSATSIM-FSK seems to have a default value from when I first downloaded the software in January because this image shows the "captured" from almost a month ago. 
![cubesat fsk](https://user-images.githubusercontent.com/69646946/108579735-eaf9ff00-72ed-11eb-852c-f3331c318089.jpg)
- Even when I start tracking AO-85, the values in the corresponding tab don't change. 
- To my knowledge, I'm able to click on temperature under Computer Hardware, for example, and I get a real time graph, but no such graph appears. (Again, this might be the CubeSat malfunctioning). To be clear, the graph itself appears but it doesn't update. 
- I tried using SDRsharp and Foxtelem at the same time, and like you said earlier, they can't both use the RTL at the same time.
- After I tried some tests in SDRsharp (which was using the port for a while) and closed SDRsharp, Foxtelem suddenly couldn't use the RTL as the "SERIOUS EDT Error" showed up. Simply closing the application and opening it up fixed the problem. Though when I opened it again, it immediately started looking for frequencies to decode. I didn't have to press start for it to start. 
- It might be important to note that I have problems with SDRsharp, causing me to reinstall a "RTL2838UHIDIR" and "USB Composite Device Driver"
- Now that I think about it, the initial version of Foxtelem you gave me might not be the only thing that fixed my USB problems. Before, I wasn't reinstalling the "RTL2838UHIDIR" and "USB Composite Device Driver" when I used SDRsharp; I installed a driver called "Bulk-In, Interface (Interface 0)", which according to the [website](https://www.rtl-sdr.com/rtl-sdr-quick-start-guide/) is interchangeable with the aforementioned drivers, so that might be something to keep in mind. 

I did have logging enabled for some of the things I tried, so let me know if having the logs might help. 
Thanks!

**Comment by ac2cz** [comment]
Thanks for the detailed report.

The Audio Missed is shown when your computer can't keep up with the data being sourced from the SDR.  It should only rarely happen and it usually corresponds with the computer being busy with other programs at the same time.  It can also happen on older hardware or if you set the RTL bandwidth to be really wide.  If you see it a lot then let me know because it could also be a bug in the new version.

I'm going to default the USB Errors to say 0 at start up.  But showing nothing in the version you have is good.  It will increment if there are errors on the USB bus,

When the CubeSatSim transmits you should be able to see the signal in FoxTelem.  There should be a bump in the red line.  You can click on the bump to manually tune FoxTelem or you can have FoxTelem automatically tune to the signal.  For the FSK CubeSatSim make sure you are in DUV mode, which is at the top of the window.  For BPSK make sure Fox/Husky mode is selected.  If FoxTelem can decode the signal then the values will change on the corresponding tab.

Good to know on the device drivers.  Those are always hard to get right.

On the sound, if you have "Squelch when no telemetry" checked then it will only play sound when it thinks it can hear a telemetry signal.  This is determined by measuring the Signal to Noise ratio of the received bits (as displayed in the eye diagram). If that is over a certain threshold then it plays the sound.  You also need to have pressed the button to "Monitor Audio" but it looks like you have done that because the text on the button has changed to "Silence Speaker".

**Comment by Nanjavi** [comment]
Got it. For that last point, in the 1.10d version, I have "squelch when no telemetry" selected, and it doesn't produce any sound, but it works fine in version 1.10d3. For me, this doesn't pose a problem at all, but I suppose it's something to keep in mind when testing for different devices. 

Thanks!
