### ISSUE TITLE
FoxTelem loosing connection to RTL-Stick

### ISSUE THREAD

**Issue by DH1OK** [ac2cz/FoxTelem#687]
Hello Chris,

I have to report problem with my Raspberry Pi and a RTL-Stick. The problem occurs after different times of running FoxTelem on the Pi. It seems to me that the software couldn't find the stick or lost the control over him. This Message occurs:
 
![grafik](https://user-images.githubusercontent.com/29518831/111067155-29d13e00-84c3-11eb-91f9-d25c6f1c119e.png)

These are the logfiles, i think : [FoxTelemetryData.tar.gz](https://github.com/ac2cz/FoxTelem/files/6136675/FoxTelemetryData.tar.gz)

I can't see the problem, maybe you have an idea?

73's de DH1OK
Olaf

**Comment by ac2cz** [comment]
Hi Olaf.  I am aware of the issue.  I think it is the same (or very similar) to #466.  There seems to be many reasons why the hardware does not respond.  I changed the software to ignore or retry the connection, but it seems that I missed some of the cases perhaps.  This is mainly an issue on the PI, perhaps because the platform is slower or the USB hardware works in a different way.

**Comment by burnsfisher** [comment]
FWIW, I see the same problem on a Windows machine.  (I did not double check the actually traceback, but the symptoms are similar).

**Comment by ac2cz** [comment]
I think I now catch and retry this situation.  It will be in the next release or the development version from 1.12k.

**Comment by ac2cz** [comment]
I'm going to close this as it appears to be stable now.
