### ISSUE TITLE
Fox-1E rotation inconsistent between health and WOD screens

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#694]
This appears to be the formula used for the decode.  I suspect health is correct because WOD change very little, unlike other Fox satellites.  (I could be wrong though).

They (all gyro values) are also incorrect on LTM WOD vs realtime but ok on Golf-TEE.  Some of this on Golf and LTM may be my formulae

**Comment by ac2cz** [comment]
I looked at this.  Both layouts are using the same conversion.  It is legacy conversion 13 which is called CONVERT_MEMS_ROTATION within FoxTelem.  But something strange is going on.

On the WOD tab a raw value of 2120 gives a rotation of 45.5
On the Health tab a raw value of 2129 gives -0.2

Stepping through the code I realized that in the RT layout the field is called SatelliteXAxisAngularVelocity and in the WOD it is called Xvelocity.  That is only important because we store the rest values for the gyros and I need a way to associate the rest values back with each axis.  So it looks for a rest value that corresponds with Xvelocity and does not find one.  Rather than default to the datasheets 1.51V it uses 0!

It is probably right that it uses 0 rather than the datasheet value because it is a bug.

The solution is to change the names in the layout for WOD.  I have made them:
SatelliteXAxisAngularVelocity
SatelliteYAxisAngularVelocity
SatelliteZAxisAngularVelocity

I don't think it matters at this point that the names now differ from the master spreadsheet and the C code.  This is just something needed to make the conversion work.  Let me know if you see an issue.  

I will release this as 1.11g2 and the only change will be to this file.

**Comment by burnsfisher** [comment]
This seems kind of odd to me.  The WOD and the Realtime layouts both come
from the same spreadsheet (common) don't they?  Or maybe that was so long
ago that it worked differently on Fox?

In any case, I see no issue--I'm never going to create those header or
layout files again from the spreadsheet.

**Comment by ac2cz** [comment]
Hmm, this is of course harder on the server.  The column names in the SQL tables are named the same as the fields in the layout.  So it is not as simple as just changing the layout file.  So I need to stop the server at some point and rename the database columns too.   So for now this is wrong on the WOD page on the website.

**Comment by burnsfisher** [comment]
Looks good on Fox-1E.  I'm not sure about my comment regarding LTM.  That should not have the same issue.  A quick look at 12h2 makes it seem ok, but I have not played with it for a while.  I'll close this and open a different one later LTM has the same problem.
