### ISSUE TITLE
Errors on first frame of 'safe mode' frame pair

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#695]
On V1.12c, the first of a safe mode pair of frames nearly always has a lot of errors and erasures--sometimes so many it is not decoded at all.

I tried decoding the 1E flight unit recordings and saw very similar behavior.  I also tried it with older versions of FoxTelem.  At first I thought that the older versions were better, but as time went on I'm less sure.  The same with Costas vs Dot Product...I can't say for sure that one is better.

What DOES seem better is that if you run the 1E recordings at high speed (not recommended :-)  I get better decodes.

This whole thing is somewhat inconsistent so take many of my "this works better than this" with a grain of salt.  Do note, though, that is was likely the trigger for other crashes that were reported (and fixed) in a #693 .  So whatever I reported there (like deleting saved data) as making a change probably makes a change in this case too.

**Comment by ac2cz** [comment]
I'm looking at potential fixes for a 1E release.  Is this still an issue?  Should it just be tagged Golf or 1E as well?

**Comment by burnsfisher** [comment]
No idea if it is a problem with 1E, but it is a problem with both LTM and
Golf.  Can we add an LTM label?  I think there may be another one that
should be LTM also.

**Comment by ac2cz** [comment]
LTM label added.  I'll investigate and see if there is a systemic issue that was across spacecraft.

**Comment by ac2cz** [comment]
LTM label added.  I'll investigate and see if there is a systemic issue that was across spacecraft.

**Comment by ac2cz** [comment]
Version 1.12k tightens the frequency range for the PSK carrier search to +- 300Hz.  The time to acquire the signal is almost directly proportional to the range of frequencies that are searched.  Tightening the range produces reliable decode of both beacon packets at the expense of more accurate tuning.

Previously the Costas Decoder searched 4KHz.  The Dot Product Decoder searched 1.6kHz.  Both now search 600Hz.

This should be tested carefully.  It will make the decode of Health frames apparently worse because mistuning the signal will drop a significant number of frames, when previously just the first one could be lost.  But it will deliver 2 frames from a well tuned beacon signal, when previously one was lost even if the signal was tuned in very accurately.  

I will mark it as "Fixed" but really I mean available for testing..

**Comment by burnsfisher** [comment]
I intentionally set the decode frequency way off, and told it to track a satellite whose frequency matched my bench setup.  Find signal is also set.  In safe mode, as soon as the transmitter came on, the decode frequency jumped to the right location, and I got both safe mode frames.  Yay!
