### ISSUE TITLE
Crash when using arrow key to move through Science CAN messages

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#720]
This is the in partner science data as you can see.  I chose a row (at the bottom) at random, and then clicked on one of the specific CAN messages above.  That's ok.  But then I used an arrow key to try to scroll down (to count messages) and kaboom.

This is 1.12o with my added layout info (same as you pulled a few days ago
![Screenshot 2021-11-16 16 25 43](https://user-images.githubusercontent.com/2413372/142082859-18ac9e52-6e8d-4626-8fc4-a77ee4d321d8.png)
).

**Comment by ac2cz** [comment]
I can reproduce this and the fix is done.  I will be in 1.12p.

Clicking on the CAN packets does not do anything other than select the row in the table.  Using the arrow keys now moves the selected row but does nothing else.  If you want to scroll through the payloads you then need to click back on the table at the bottom of the window.

**Comment by burnsfisher** [comment]
Thanks.  The reason I was using the arrow keys on the individual CAN messages was to count them, i.e. to scroll below the bottom of that window.  I'm hoping that this is part of what you fixed.

**Comment by burnsfisher** [comment]
Looks good.  Thanks!
