### ISSUE TITLE
Another failure to open SDR

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#750]
I can't find this, although I'm pretty sure there is another issue like it.  FoxTelem stopped because it said the soundcard was not available.  It appears not to have tried 5 times (only 1 according to the data line at the bottom).

<img width="1075" alt="Screen Shot 2022-09-05 at 2 46 56 PM" src="https://user-images.githubusercontent.com/2413372/188502372-1343be1b-f72a-463c-a2b9-d14832735329.png">

**Comment by ac2cz** [comment]
Actually I think it did retry 5 times. The counter at the bottom is confusingly split into two. The first number is the fatal issues that result in this error.  The second number is the number of retries.  The first number may not be needed I suppose.

So this is expected behavior.  There was an error on the USB bus that caused this to be unavailable.  I could consider increasing the delay between retries. What do you think?  Right now it waits 200ms between retries.  That seems to work for the normal situation where a bit of noise on the bus caused the first try to fail.  But should it wait longer and longer on each try?

**Comment by burnsfisher** [comment]
Oh, so the '1' means that all 5 problems were the same thing. It's possible
this is "real".  I'm trying to get it back online remotely and even a
reboot does not seem to help.  Maybe it needs a full power cycle.   I'll
let you know.

**Comment by burnsfisher** [comment]
Very odd.  I just unplugged the FCDPP and replugged it in another USB socket and then rebooted the Pi.  Same behavior.  I have it set so it does not autostart now.  I push the start button and everything looks ok EXCEPT there is nothing in the RF or the AF windows.  I stop and start again, and I get the message above and again a 1/5.  I wonder if my FCDPP is dead?  Maybe tomorrow I'll try a different one and/or an RTLSDR.

**Comment by burnsfisher** [comment]
YES!  Switching to DUV, stopping and restarting FoxTelem solved it.  (Just
switching did not solve the problem until I restarted it).  Odd that it
failed after running for several weeks.  Anyway, I'll pull 1.12y.

**Comment by ac2cz** [comment]
Ok, thanks good.  Then I am going to mark this as fixed in 1.12y and you can confirm that.

**Comment by burnsfisher** [comment]
I have not seen this problem on 1.12z.
